### ISSUE TITLE
Page Forms: Error: Call to private method EditPage::tokenOk() from context 'PFAutoeditAPI'

### ISSUE THREAD

**Issue by vid** [radiorabe/docker-mediawiki#116] opened 2022-11-15 15:56 UTC
Hi! I am basing some work on your repo, thank you! Most of the docker files are unchanged.

I have created some forms, on submission I see the title error. I would guess this is a mismatch between Page Forms and mediawiki versions. Do you have a solution?

Here is the backtrace:

```
Backtrace:

from /var/www/html/extensions/PageForms/includes/PF_AutoeditAPI.php(447)
#0 /var/www/html/extensions/PageForms/includes/PF_AutoeditAPI.php(1015): PFAutoeditAPI->doStore()
#1 /var/www/html/extensions/PageForms/includes/PF_AutoeditAPI.php(129): PFAutoeditAPI->doAction()
#2 /var/www/html/extensions/PageForms/specials/PF_FormEdit.php(103): PFAutoeditAPI->execute()
#3 /var/www/html/extensions/PageForms/specials/PF_FormEdit.php(44): PFFormEdit->printForm()
#4 /var/www/html/includes/specialpage/SpecialPage.php(671): PFFormEdit->execute()
#5 /var/www/html/includes/specialpage/SpecialPageFactory.php(1378): SpecialPage->run()
#6 /var/www/html/includes/MediaWiki.php(315): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#7 /var/www/html/includes/MediaWiki.php(912): MediaWiki->performRequest()
#8 /var/www/html/includes/MediaWiki.php(563): MediaWiki->main()
#9 /var/www/html/index.php(53): MediaWiki->run()
#10 /var/www/html/index.php(46): wfIndexMain()
#11 {main}
```

And the relevant parts of Dockerfile
```
ENV MEDIAWIKI_EXT_BRANCH REL1_38
…
# Install composer based extensions
RUN cd /var/www/html/ \
     && composer require mediawiki/semantic-media-wiki "~4.0.2" --update-no-dev \
     && rm composer.lock \
     && composer require mediawiki/semantic-result-formats "~4.0" --update-no-dev \
     && composer require mediawiki/semantic-compound-queries "~2.2" --update-no-dev \
     && composer require mediawiki/graph-viz "^2.0" --update-no-dev
# && composer require jumbojett/openid-connect-php "0.9.5" --update-no-dev
…
RUN git clone --depth=1 -b $MEDIAWIKI_EXT_BRANCH https://gerrit.wikimedia.org/r/mediawiki/extensions/PageForms.git /var/www/html/extensions/PageForms
```

Thanks!

**Comment by hairmare** [comment] 2022-12-25 14:03
I can't seem to be able to reproduce your issue, but I also haven't updated to 1.38 yet due to incompatibilities with SemanticMediaWiki and am not using much PageForms anymore these days. Maybe a version that is [supported by SemanticMediaWiki](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md) works.

The tokenOk method from your error seems to have been privated in https://github.com/wikimedia/mediawiki/commit/a071d2c062f2cbff3ba7e0094f085de88805d6da which seems to have happened with 1.39 earlier this year.  Is is possible that you EXT_BRANCH REL1_38 doesn't match the mediawiki version? If you want to live on the hacky side you could also consider just removing the `private` on the `tokenOk` method but be aware that this might have even worse side-effects given that `tokenOk` looks somewhat security related.

For my deployment i kinda regret having updated past 1.35 TLS given that there are quite some incompatibilities with SemanticMediaWiki. I'm hoping that i can move to 1.38 or 1.39 early next year when php 8.1 is supported by SemanticMediaWiki but am not currently holding my breath.

**Comment by hairmare** [comment] 2024-01-13 00:11
closing this since i updated to 1.39 which might have fixed the issue at hand

**Closed by hairmare** 2024-01-13 00:11 UTC
